Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 100

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'app/views/**/*.jbuilder'

Style/ExpandPathArguments:
  Exclude:
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'config/environment.rb'
    - 'config/application.rb'

Metrics/ParameterLists:
  Exclude:
    - app/**/*

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - config/environments/*
    - config/initializers/*
    - node_modules/**/*
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - config/boot.rb
    - config.ru
    - config/application.rb
  CacheRootDirectory: tmp/
